### ISSUE TITLE
Add support to repeat items with no new line inserted

### ISSUE THREAD

**Issue by anthonygerrard** [malthe/chameleon#110]
tal:repeat always inserts a new line inbetween repeating elements.  Whitespace is sometimes important in HTML and unnecessary whitespace can cause styling problems in some older browsers.

It would be great if Chameleon could support repeating elements, or text, all on the same line.

The equivalent bug in zope.tal project is https://bugs.launchpad.net/zope3/+bug/229931

It seems tricky to do this in a backwards compatible way.  A rule that would make sense to me would be that if the repeating element is the first non white space element on its line then add a new line otherwise don't.

e.g.

``` xml
    <ul><li tal:repeat="item items" tal:content="item"></li></ul>
```

would result in

``` xml
    <ul><li>item 1</li><li>item 2</li><li>item 3</li></ul>
```

but

``` xml
    <ul>
        <li tal:repeat="item items" tal:content="item"></li>
    </ul>
```

would result in

``` xml
    <ul>
        <li>item 1</li>
        <li>item 2</li>
        <li>item 3</li>
    </ul>
```

**Comment by malthe** [comment]
I think this is fixed or at least resolved.
