### ISSUE TITLE
appengine does not allow debug module loader

### ISSUE THREAD

**Issue by jensens** [malthe/chameleon#130]
While developing for appengine in debug mode i have to disable the module loader, because it uses a tempdir. in details this monkey patch helps:

```
# disable chameleon debug module loader, gae does not allow tempdirs
import chameleon.template
from chameleon.loader import MemoryLoader

chameleon.template._make_module_loader = MemoryLoader
chameleon.template.BaseTemplate.loader = MemoryLoader() 
```

maybe a module loader using a different mechanism could be invented.

**Comment by malthe** [comment]
The default behavior in non-debug mode now is to use the memory loader so I think this issue is obsolete.
