### ISSUE TITLE
Path expression segments starting with digits

### ISSUE THREAD

**Issue by davisagli** [malthe/chameleon#134]
z3c.pt uses this regexp to validate path expressions:

```
    path_regex = re.compile(
        r'^(?:(nocall|not):\s*)*((?:[A-Za-z_][A-Za-z0-9_:]*)' +
        r'(?:/[?A-Za-z_@\-+][?A-Za-z0-9_@\-\.+/:]*)*)$')
```

This means that a segment of the path cannot start with a digit. That was supported in the reference implementation. (I have a template called 40years.pt and used to be able to use its macros, but cannot with chameleon.)

**Comment by malthe** [comment]
Seems this was already fixed years ago so we can close the issue here.
