### ISSUE TITLE
Please remove pagetemplates.org from setup.py

### ISSUE THREAD

**Issue by zopyx** [malthe/chameleon#137]
Your site pagetemplates.org is very often not available and causes global buildout problems due to the fact that you reference the site as 'url' in your setup.py. Please point 'url' to PyPI and add a link to your site in the README file. It annoyed me today, a co-worker and  a n00b on IRC:

**Comment by viniciusban** [comment]
Sorry, but I think this issue should be closed, right?

**Comment by zopyx** [comment]
No idea :)

**Comment by malthe** [comment]
That link is no longer there now – it's been replaced in 5ea23b2 with a link to the [documentation](https://chameleon.readthedocs.io).
