### ISSUE TITLE
html javascript template for attribute within <button> ParseError

### ISSUE THREAD

**Issue by Yakumounr** [malthe/chameleon#147]
The below html template is from jQuery-File-Upload-8.2.1\index.html from https://github.com/blueimp/jQuery-File-Upload

``` HTML+ERB
<button class="btn btn-danger delete" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.delete_with_credentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                <i class="icon-trash icon-white"></i>
                <span>Delete</span>
            </button>
```

when rendered with Chameleon via Pyramid this gives -

``` HTML+ERB
chameleon.exc.ParseError
ParseError: Unexpected end tag.

 - String:     "</button>"
 - Filename:   c:\pi\jquery-file-upload-8.2.1\server\pyramid-jquery-file-upload-demo\pyramidpython\imageupload.pt
```

Because of the template code within the `<button>`

The following is a suboptimal work arround -

``` HTML
        {% if (file.delete_with_credentials) { %}
            <button class="btn btn-danger delete" data-type='{%=file.delete_type%}' data-url='{%=file.delete_url%}' data-xhr-fields='{"withCredentials":true}'>
            {% } %}

         {% (!file.delete_with_credentials) { %}
            <button class="btn btn-danger delete" data-type='{%=file.delete_type%}' data-url='{%=file.delete_url%}' >
            {% } %}
```

I found this issue as the template html file ('index.html') is  symlinked to and loaded as 'imageupload.pt' using Chameleon by the Pyramid bare bones demo application for jquery-file - https://github.com/grooverdan/pyramid-jQuery-File-Upload-demo

**Comment by malthe** [comment]
Looking at this again I see that you're using unsupported characters inside a tag, namely `{%` and `%}`. That's not allowed and Chameleon does not currently support that.
