### ISSUE TITLE
attribute injection does not work.

### ISSUE THREAD

**Issue by reebalazs** [malthe/chameleon#162]
consider this template:

``` html
<input ${attr} type="text">
```

with the following data:

``` python
{'attr': 'disabled'}
```

This should generate

``` html
<input disabled type="text">
```

but it doesn't, instead it silently fails and it looks like the processing stops on this line and nothing else will be processed.

At the same time I noticed that tal:attributes="{....}" does work with the dictionary keys and values correctly expanded to attribute names and values. So, this is the workaround that I am using right now in the feature.angular branch of deform where I need to inject variable html attributes. But it would be neat to use the natural form.

**Comment by malthe** [comment]
I'll close this issue because I don't think it's particularly important given that you can pass a dictionary to `tal:attributes` which is much more powerful.

**Comment by reebalazs** [comment]
Thanks @malthe! Sadly, I have not much interest in chameleon any more, since I am working with client side templating these days.

**Comment by malthe** [comment]
Yep, totally understand. Just cleaning up issues!
