### ISSUE TITLE
Windows line endings cause parse errors that don't occur with *nix line endings

### ISSUE THREAD

**Issue by anthonygerrard** [malthe/chameleon#174]
For example

```
            <button\r\n
                id="testStylesButton"\r\n
                class="standalone"\r\n
                i18n:translate="">Test Styles</button>
```

causes a problem whereas

```
            <button\n
                id="testStylesButton"\n
                class="standalone"\n
                i18n:translate="">Test Styles</button>
```

does not.

you get an error like

Traceback (innermost last):
    ...
    Module zope.pagetemplate.pagetemplate, line 126, in pt_render
    Warning: Compilation failed
    Warning: chameleon.exc.ParseError: Unexpected end tag. - String: "</button>" - Filename: ... - Location: (line xx: col xx)

PTRuntimeError: ['Compilation failed', 'chameleon.exc.ParseError: Unexpected end tag.\n\n - String: "</button>"\n - Filename: ...\n - Location: (line xx: col xx)']

**Comment by davilima6** [comment]
+1 here

Traceback (innermost last):

Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module esp.library.browser.theme_changer, line 48, in __call__
Module Products.Five.browser.pagetemplatefile, line 125, in __call__
Module Products.Five.browser.pagetemplatefile, line 59, in __call__
Module zope.pagetemplate.pagetemplate, line 126, in pt_render
Warning: Compilation failed
Warning: chameleon.exc.ParseError: Unexpected end tag. - String: "</span>" - Filename: /vagrant/src/my/product/browser/my_template.pt - Location: (line 80: col 24)
PTRuntimeError: ['Compilation failed', 'chameleon.exc.ParseError: Unexpected end tag.\n\n - String: "</span>"\n - Filename: /vagrant/src/my/product/browser/my_template.pt\n - Location: (line 80: col 24)']
