### ISSUE TITLE
CHAMELEON_DEBUG usage results in warning

### ISSUE THREAD

**Issue by wichert** [malthe/chameleon#183]
Trying to start a Pyramid app with CHAMELEON_DEBUG set (as mentioned in [the documentation](https://chameleon.readthedocs.org/en/latest/configuration.html#development)) results in a warning:

```
$ CHAMELEON_DEBUG=1 bin/pserve site.ini 
17:01:06 WARNI [chameleon.config] unknown environment variable set: "CHAMELEON_DEBUG".
```

**Comment by icemac** [comment]
This was fixed in Chameleon version 2.19.
