### ISSUE TITLE
auto_reload configuration argument not mentioned in API docs

### ISSUE THREAD

**Issue by faassen** [malthe/chameleon#188]
The auto_reload configuration argument does not appear to be listed in the API docs. Is this not intended to be part of the public API? (and if not, why not?)

**Comment by malthe** [comment]
I believe it's an oversight.

**Comment by faassen** [comment]
Good to hear I'm busy integrating Chameleon into Morepath with the more.chameleon extension, and I was getting worried I was relying on something hidden. But that's fine then.

Here's the integration code:

https://github.com/morepath/more.chameleon

**Comment by malthe** [comment]
Oh nice. It's definitely a supported feature – used also by Pyramid's ZPT integration.

**Comment by malthe** [comment]
Fixed in cbb391b.
