### ISSUE TITLE
zpt.loader.TemplateLoader versus  loader.TemplateLoader

### ISSUE THREAD

**Issue by faassen** [malthe/chameleon#189]
I'm trying to understand something in the code. In chameleon.zpt.template there is this import:

```
from ..loader import TemplateLoader
```

so this loads the loader from `chameleon.loader`, not `chameleon.zpt.loader`, and subsequently it is used as the default loader class for `PageTemplateFile`.

But `chameleon.zpt.loader` actually subclasses the core `TemplateLoader`. This is the loader exposed in the public API as `PageTemplateLoader`. But it appears it's not used internally.

Is that intentional? It's rather confusing why it may be so.

**Comment by malthe** [comment]
The reason for this pattern is that often times people subclass ``PageTemplateFile``. This class then uses the base loader and does the following:
```python
template_class = type(self)
self._loader = loader.bind(template_class)
```
This way, you can use a custom loader if you wanted to and it also works with subclassing of the page template class itself.

**Comment by faassen** [comment]
So what's the point of PageTemplateLoader? Who is supposed to use it?

**Comment by malthe** [comment]
The point of a ``PageTemplateLoader`` is if you want to provide a function such as:
```python
def render_template(spec, **kw):
    template = template_loader.load(spec)
    return template.render(**kw)
```

**Comment by faassen** [comment]
Okay, I'm using it correctly then. I got confused as PageTemplateLoader is a public API to load templates, while it subclasses from TemplateLoader which is only intended for 'load' expressions. I can see why the subclass relationship is there, but on the other hand the concerns (and some of the parameters) are actually quite different.

**Comment by malthe** [comment]
It's a little confusing, I'll definitely give you that. It was supposed to be very clear but then a bunch of frameworks wanted nice integration points :-)

**Comment by malthe** [comment]
Closing this since the functionality is documented here https://chameleon.readthedocs.io/en/latest/library.html#loader.
