### ISSUE TITLE
load expression does not respect full search_path

### ISSUE THREAD

**Issue by faassen** [malthe/chameleon#191]
As far as I understand, search_path in Chameleon exists to give it a list of directories from which to attempt to load templates, items earlier in the list overriding later ones. 

This works as expected with PageTemplateLoader, but if a loaded template then loads something using the load expression, it only gets the path from the template, not the full search_path.

This means that if you load a macro with a load expression, it isn't possible to override which macro gets loaded by adding another directory to the search path.

Shouldn't line 85 of ```chameleon/loader.py``` read like this?

```
                return cls(self.search_path, **self.kwargs)
```

**Comment by faassen** [comment]
Okay, my suggestion didn't work. I'm still trying to figure out how to make the load expression respect the same search path as I used in the PageTemplateLoader.

**Comment by malthe** [comment]
It's supposed to use the ``__loader`` of the calling template and so it shouldn't matter what the macro template *would* use if it was called directly.

**Comment by faassen** [comment]
Okay, the required change is the following:

```
                return cls(path, search_path=self.search_path, **self.kwargs)
```

This still doesn't work, as ```prepend_relative_search_path``` is set to True which makes the loader still look in the wrong place, but when I disable that, things work as I expected.

Would it be possible to integrate the search_path change into Chameleon?
