### ISSUE TITLE
[RFE] Support HTML5 data- attributes syntax

### ISSUE THREAD

**Issue by PyDeq** [malthe/chameleon#197]
HTML5 supports usage of [custom attributes](https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute). This way we could be able to produce Chameleon templates that are valid HTML5 documents. It would be nice if Chameleon could have TAL attributes renamed or have aliases compatible with HTML5 specification (e.g. ```data-tal-repeat="item sequence"``). E.g. [Google+](https://developers.google.com/+/web/+1button/) and [Facebook](https://developers.facebook.com/docs/plugins/like-button) uses these attributes.

**Comment by malthe** [comment]
But Chameleon templates will never make it to a browser – which actually understands and cares about whether a document is valid HTML5. What does matter is that they're valid XML so that you can utilize the existing XML toolchain.

Unless I'm missing something?

**Comment by PyDeq** [comment]
Yes, that's true. And I very much appreciate that they are valid XML.

My point is that it's such a hassle to validate HTML documents generated from templates... You need to run Python, instantiate and render the template and paste the result into the validator. If it would be possible to validate the template itself, it would make the validating process faster. I would be able to catch the major bugs before it comes to the problems caused by passing incorrect values to the template renderer.

Of course, I need to validate the rendered documents anyway. The requested feature is just nice to have. I can continue validating the templates while ignoring the ```Attribute tal:* not allowed on element p at this point.``` errors.

**Comment by malthe** [comment]
I think XSLT is the answer to this problem. Your system probably already has ``xsltproc`` installed. It should be relatively simple to pipe the input through this program before handing it over to the validator.

Pass the templates through a transform like so:
```xml
<xsl:template match="@tal:*">
    <xsl:attribute name="data-tal-{local-name()}">
        <xsl:value-of select="." />
    </xsl:attribute>
</xsl:template>
```
Note that the document must declare the ``tal`` namespaces explicitly for this to work (i.e. it must be a valid XML document).

**Comment by PyDeq** [comment]
Well, this still includes an intermediate step. It doesn't matter whether I would have to render the template or transform it via XSLT.

**Comment by malthe** [comment]
It does matter because in order to render a template you need to provide a suitable input, whereas with an XSLT transform you're not actually rendering the template.

**Comment by PyDeq** [comment]
Yes sure. But I hope that the benefit of using ```data-tal``` attributes right in the template is clear. Is there a disadvantage or another reason why it would be bad idea to implement it?
