### ISSUE TITLE
i18n:target

### ISSUE THREAD

**Issue by voxspox** [malthe/chameleon#198]
Hi,

I use chameleon as template engine with pyramid 1.4 in a multi-language application.
I want to use i18n:target to always switch to a certain language in  a certain part of the template.
Using set_locale_negotiator() of pyramid.Configurator works to switch the global locale, thus everything seems to be set-up right.
But when I use i18n:target in the template nothing happens. Even not for 'default' or 'nothing'.

knut

pyramid bug tracker: https://github.com/Pylons/pyramid/issues/1590

**Comment by malthe** [comment]
AFAIK this attribute is not implemented.

**Comment by voxspox** [comment]
If it is not implemented, the documentation should be updated accordingly.

**Comment by malthe** [comment]
Yes, or alternative, it should be implemented. Note that the issue is still open :-)

**Comment by voxspox** [comment]
Yes of course it should be implemented :)
A hint in the documentation would save developers the inconvenience and time to find out that there is no error in their code, but the feature is not implemented yet.

**Comment by mattpepin** [comment]
I ran into the same issue. A hint in the docs would certainly have been welcome. Any progress on this?

**Comment by malthe** [comment]
No progress supporting ``i18n:target`` but I have added a warning in the documentation.
