### ISSUE TITLE
Expressions types containing numbers?

### ISSUE THREAD

**Issue by tflorac** [malthe/chameleon#201]
Hi,
I wanted to create a custom expression type called "i18n" to handle internalization through a custom package.
After debugging a while, I noticed that "match_prefix" in "tales.py" doesn't recognize expressions containing numbers.
Is it a real choice?

Thanks,
Thierry

**Comment by malthe** [comment]
It's a bug; I think the only requirement should be that the prefix begin with ``[a-z]``.
