### ISSUE TITLE
documentation not updated?

### ISSUE THREAD

**Issue by gforcada** [malthe/chameleon#207]
@malthe I saw that you made a new release that contains my pull request about ``i18n:ignore`` but the documentation at http://chameleon.readthedocs.org/en/latest/reference.html seems to not have been updated...

**Comment by malthe** [comment]
I think I need to do that explicitly, hold on.

**Comment by malthe** [comment]
Version 2.24 should be building now.

**Comment by gforcada** [comment]
@malthe  thanks, that was quick!

One caveat though: the version switcher now shows a 2.24 version, but latest still does not show it...

**Comment by malthe** [comment]
Should work now.
