### ISSUE TITLE
Error in description of truthy and falsy values

### ISSUE THREAD

**Issue by piotr-dobrogost** [malthe/chameleon#211]
At http://chameleon.readthedocs.org/en/latest/reference.html one reads:

> Like Python itself, ZPT considers None, zero, empty strings, empty sequences, empty dictionaries, and instances which return a nonzero value from `__len__` or `__nonzero__` false; all other values are true, including default.

Shouldn't that be _return zero value_ instead?

**Comment by malthe** [comment]
I think it could be made more clear, yeah.
