### ISSUE TITLE
Add i18n:language attribute

### ISSUE THREAD

**Issue by wichert** [malthe/chameleon#228]
I have a situation where I need to force translation to a specific language in a template. Would it be possible to support that with a `i18n:language` attribute? Usage would look like this:

```html
<button i18n:translate="" lang="en" i18n:target="en">Continue</button>
<button i18n:translate="" lang="nl" i18n:target="nl">Continue</button>
<button i18n:translate="" lang="de" i18n:target="de">Continue</button>
```

Which would result in:

```html
<button lang="en">Continue</button>
<button lang="nl">Verder</button>
<button lang="de">Weiter</button>
```

**Comment by malthe** [comment]
Devil's advocate here: why not just translate it statically (put it right there in the template) – ?

This is also what the documentation suggests.

**Comment by wichert** [comment]
Because that breaks standard translation workflow

**Comment by malthe** [comment]
I guess if the `i18n:target` attribute is currently not used at all then it should be relatively easy to make Pyramid's default translate plugin to Chameleon look at it before it decides to negotiate for a language.

**Comment by wichert** [comment]
Chameleon does not pass target to the translator. This is the call generated by Chameleon:

```python
-> __append(translate(__msgid_4464057808, mapping=None, default=__msgid_4464057808, domain=__i18n_domain, context=__i18n_context))
```

Since target is not passed to the translate function, pyramid_chameleon can not do anything with it.

**Comment by wichert** [comment]
For what it's worth this is my current workaround in all its evilness:

```python
    def template_data(self):
        msg = _(u'Continue', context='button')
        request = self.request
        orig_locale = request.locale_name
        continue_labels = {}
        try:
            for l in SUPPORTED_LOCALES:
                request.locale_name = l 
                continue_labels[l] = request.localizer.translate(msg)
                del request.localizer  # Reset reified localizer
        finally:
            request.locale_name = orig_locale
        return {
            'continue_labels': continue_labels
        }   
```

**Comment by malthe** [comment]
I believe the argument to translate should end up being `target_language` – is that correct?

There is a potential issue in that you can "curry" a target_language to the render method and have it be pre-applied to the default translate-function. The concern is then that if you use `i18n:target` you can't override that language (it would be an error).

Perhaps passing `target_language` should simply be deprecated such that you must provide a translate function that correctly applies a default language for that render.

**Comment by malthe** [comment]
@wichert this should help you ^^^

**Comment by wichert** [comment]
@malthe That looks useful. I'll try to look at the pyramid integration side of that this week.

**Comment by malthe** [comment]
Great. There really should be no difference to Pyramid. The API has been preserved.

**Comment by mattpepin** [comment]
Is there a way to make it a dynamic attribute? I can't use for example:

`<html i18n:target="${locale}">`

Without it, it's not much use with Pyramid, I guess...

**Comment by malthe** [comment]
I think it actually is dynamic. You should be able to use `i18n:target="locale"` – at least judging by the tests which use `i18n:target="string:fr"`.
