### ISSUE TITLE
instrospection of passed data

### ISSUE THREAD

**Issue by jgmtzmd** [malthe/chameleon#233]
hi. this is not a bug report but a suggestion.
i am just starting to use and like pyramid+chameleon.
it would be useful to have some list of the keys of the dictionary passed to the template. i found this keys in locals() but they come with a lot of other variables and that way we the user cant do things like iterate over the variables and such. i think its not neccesary to break anything in your code, just add to locals some list called 'passed_vars' where we can see them.

other thing i found is that i could not retrieve attribute from an ordered dict using the python (dotted) notation. i had to use __getattribute__().

regards.

**Comment by malthe** [comment]
Try "econtext" — it's a dict that holds your local scope variables.

And yes, in Python you can't access dict entries through attribute lookup.
One reason is that your keys can be any hashable object and not just
strings (or valid attribute strings even).

It's true that in some template languages, they rewrite the dot operator to
attempt dictionary lookup. This is magic, impacts performance and could
easily confuse the user.

**Comment by jgmtzmd** [comment]
yes i tried econtext but i think it mixed the passed variables with the ones i create on the template. i think it will be more confortable to have an easy way to dissern one and another. anyway its just a minor suggestion.

**Comment by jgmtzmd** [comment]
thanks for answering. im closing the ticket now.
