### ISSUE TITLE
filter in repeat

### ISSUE THREAD

**Issue by jgmtzmd** [malthe/chameleon#235]
hi.
not really a bug report but a question instead.
i am creating a table, i populated the columns like this..

        <tr tal:repeat="x resultados">            
            <td tal:repeat="k x.keys()">
                    ${x[k]}
            </td>
        </tr>

but i want to omit some columns so i did..

        <tr tal:repeat="x resultados">            
            <td tal:repeat="k x.keys()">
                <div tal:condition="k!='OPERADOR'">
                <div tal:condition="k!='TIPO'">
                <div tal:condition="k!='NUM SERIE'">
                    ${x[k]}
                </div></div></div>
            </td>
        </tr>

and it worked. but what i really want to filter out like 20 or 30 columns so this approach becomes really cumbersome.

i also tried defining a variable (list)

tal:define="omit 'OPERADOR' 'TIPO'"

and condition the repeat operation to

tal:condition="k in omit"

but seems like the 'in' operation doesnt work here.

any suggestion to how to filter out in a more pythonic way?

**Comment by malthe** [comment]
You have a bug in your `tal:define`. It should have a comma in-between the two strings.

In Python, two strings appearing next to each other like that simply concatenate to a single string. That means your `in` test fails because `omit` is "exploded" to a list of individual letters.

**Comment by jgmtzmd** [comment]
thanks. working well now.
