### ISSUE TITLE
Support for `macroname`?

### ISSUE THREAD

**Issue by jamadden** [malthe/chameleon#238]
The Zope TAL implementation [automatically provides the `macroname` variable](https://github.com/zopefoundation/zope.tal/blob/master/src/zope/tal/talinterpreter.py#L895) during the scope of execution of the macro, although this seems to be undocumented. However, this is used by some existing Zope templates, such as [the main layout of zope.app.rotterdam](https://github.com/zopefoundation/zope.app.rotterdam/blob/master/src/zope/app/rotterdam/template_tablelayout.pt#L95). Chameleon doesn't provide this variable, preventing it from running such templates.

Is this something Chameleon could/would/should do? If so, I would be happy to work on a PR to add that (although I might need some guidance).

**Comment by malthe** [comment]
You'll need to use `wrap` on `slot` in the following line with a `nodes.Define` for `macroname` that's statically assigned to the `clause` value.

https://github.com/malthe/chameleon/blob/master/src/chameleon/zpt/program.py#L558
