### ISSUE TITLE
question: can i pull blocks from some base template?

### ISSUE THREAD

**Issue by jgmtzmd** [malthe/chameleon#241]
hi.

i hope you can clarify this to me:
is there a way to use blocks stored in other template file?

i know i can relay use:
`    metal:use-macro="load: other_file.pt"`
and 
`    metal:fill-slot="some_slot"`
so we get an "other_file.pt"-like template with the slot content replaced.

but what if i want to have a file, call it "base.pt" where i store different blocks (macros?) and let the rest of the templates ("template1.pt", "template2.pt".. etc) load different blocks from it. is it possible? how? i tried things like 
`    metal:use-macro="load base.pt['some_block']" `

i already read the docs and trial-errored this. unsuccesfully.

**Comment by malthe** [comment]
Hi. You can use `tal:define="other load: other_file.pt"` and then `metal:use-macro="other.macros['some_block']"`.

**Comment by jgmtzmd** [comment]
it worked. great!

thanks a lot.

not sure if its me or the docs are not clear enough. neither did i find in docs where it states the use of ".macros". Besides that, great job with chameleon. in my opinion far better than the alternatives.

**Comment by malthe** [comment]
The docs aren't very good, so we try to make up for it here in the issue tracker :-)
