### ISSUE TITLE
Compiler error replaced expression with `str()`

### ISSUE THREAD

**Issue by hathawsh** [malthe/chameleon#244]
I was quite surprised to discover today that Chameleon (version 3.1 on Python 3.5.2) had mis-compiled a template I've been using heavily for years. When I deleted the cached compiled module, Chameleon re-created the template correctly. I saved the mis-compiled module for further study.

The template is checkbox_choice.pt from Deform 2.0a2. Here it is, unchanged:

```
<div tal:define="css_class css_class|field.widget.css_class;
                 style style|field.widget.style;
                 oid oid|field.oid;
                 inline getattr(field.widget, 'inline', False)"
     tal:omit-tag="not inline">
  ${field.start_sequence()}
  <div tal:repeat="choice values | field.widget.values"
       tal:omit-tag="inline"
       class="checkbox">
    <label for="${oid}-${repeat.choice.index}"
           tal:define="(value, title) choice"
           tal:attributes="class inline and 'checkbox-inline'">
      <input tal:attributes="checked value in cstruct;
                             class css_class;
                             style style"
             type="checkbox"
             name="checkbox"
             value="${value}"
             id="${oid}-${repeat.choice.index}"/>
      ${title}
    </label>
  </div>
  ${field.end_sequence()}
</div>
```

The problem was in the call to field.end_sequence(); Chameleon wasn't calling it. I looked at the compiled module and here's what I found:

```
           # <Interpolation value=<Substitution '\n  ${field.end_sequence()}\n' (22:8)> braces_required=True translation=False at 7fb5daabacf8> -> __content_140419459435464
            __token = ('${field.end_sequence()}', 23, 2, '/srv/wcbuild/eggs/deform-2.0a2-py3.5.egg/deform/templates/checkbox_choice.pt', )
            __token = ('field.end_sequence()', 23, 4, '/srv/wcbuild/eggs/deform-2.0a2-py3.5.egg/deform/templates/checkbox_choice.pt', )
            __content_140419459435464 = str()
            __content_140419459435464 = __quote(__content_140419459435464, '\x00', '&#0;', None, False)
            __content_140419459435464 = ('%s%s%s' % ('\n  ', (__content_140419459435464 if (__content_140419459435464 is not None) else ''), '\n', ))
            if (__content_140419459435464 is None):
                pass
            else:
```

I thought the code was very peculiar since I couldn't see where it was actually calling `field.end_sequence()`. I moved the module aside and regenerated it. Here's what Chameleon generated this time:

```
           # <Interpolation value=<Substitution '\n  ${field.end_sequence()}\n' (22:8)> braces_required=True translation=False at 7fc81c1717b8> -> __content_140497844064920
            __token = ('${field.end_sequence()}', 23, 2, '/srv/wcbuild/eggs/deform-2.0a2-py3.5.egg/deform/templates/checkbox_choice.pt', )
            __token = ('field.end_sequence()', 23, 4, '/srv/wcbuild/eggs/deform-2.0a2-py3.5.egg/deform/templates/checkbox_choice.pt', )
            __content_140497844064920 = _lookup_attr(getitem('field'), 'end_sequence')()
            __content_140497844064920 = __quote(__content_140497844064920, '\x00', '&#0;', None, False)
            __content_140497844064920 = ('%s%s%s' % ('\n  ', (__content_140497844064920 if (__content_140497844064920 is not None) else ''), '\n', ))
            if (__content_140497844064920 is None):
                pass
            else:
```

Ah, that's a lot better! Instead of `str()`, Chameleon calls `field.end_sequence()` using the expression `_lookup_attr(getitem('field'), 'end_sequence')()`. That one expression is completely different for no apparent reason.

The question is this: how in the world did Chameleon generate such errant code? Did some kind of exception happen in the middle of the compilation and Chameleon reacted by replacing the exception with `str()`? Maybe Python was momentarily out of memory, or cosmic ray, or... ???

Other details that may be relevant:
- This happened inside a Docker container. I just started using Docker volumes and the cached compiled code is now in a volume, so from Chameleon's POV, the cached compiled code is in a different filesystem than the template. I don't know how this detail would be relevant, but Chameleon has been solid as a rock for years until yesterday and yesterday is when I started using volumes.
- As of 2 days ago, both the template and the cached compiled code are stored using the XFS filesystem. Previously they were in ext4, I think.
- The machine where this is running has reported machine check exceptions before, so I can't rule out a bit flip or miscalculation. What's surprising is that it replaced the expression with `str()` rather than garbage.
- I am the only one who has shell access to the server. (I hope! ;-) )

Does anyone have any ideas how this mis-compilation might be possible?

**Comment by hathawsh** [comment]
FWIW, I did a quick grep for any other cached Chameleon modules containing `str()`. There are 10 Docker containers running similar software, with a total of 1941 cached Chameleon modules, and `str()` doesn't occur in any of them. At least the error seems to have happened only once.

**Comment by malthe** [comment]
Cosmic rays, perhaps.

It seems funky. I can't really put a finger on how it might happen. There should be "total integrity" within a single Python process due to how the ids are generated. Perhaps Python runs a garbage collection routine in the middle and somehow this triggers an unknown bug in the code that sort of keeps track of what symbols are supposed to go where when generating the code.

But without repeatability, it's difficult to be certain.

**Comment by hathawsh** [comment]
OK, thanks for thinking about it. I'll close this. If I see it again and I can find some pattern, I'll re-open it.
