### ISSUE TITLE
chameleon does not work if sourcecode is not available

### ISSUE THREAD

**Issue by mrh1997** [malthe/chameleon#246]
On systems where only .pyc files were delivered (.py sources are not available) chameleon does not work. This is i.e. the case when I try to pack a project via [cx_freeze](https://anthony-tuininga.github.io/cx_Freeze/) or similar deployment tool (the bug is already reported [here](https://sourceforge.net/p/cx-freeze/mailman/message/29779171/).

The reason is that the `codegen.template()` when used as decorator tries to get the source code of a decorated function and translates it into an AST. Currently template() is mainly used to enclose strings which does not cause problems. But in `compiler.py` there are 7 deorated functions (starting with emit*()) that cannot be processed without the sourcecode.

My proposal: instead of using tempate as decorator for functions we could use it as regular function with string parameter:

```
@template
def emit_node(node):  # pragma: no cover
    __append(node)
```

would become:

```
emit_node = template("__append(node)", params=['node'])
```

The disadvantage would be, that when debugging you cannot step through the function body of emit_node any more. But on the pro side there is less magic that can cause problems. If you agree with my proposal I could do a fix...

**Comment by malthe** [comment]
I think an alternative might be to simply return a tree structure of almost-ready AST nodes. I think what `template` does is some convenient variable substitution but that's nothing that couldn't also be done by an AST transformer class.

**Comment by mrh1997** [comment]
If I understood you correctly you propose to omit the parse step in template and define all emit functions as ast trees manually.

But there are [pretty long emite-functions](https://github.com/mrh1997/chameleon/blob/da962ceb7b6a7d16660d0ba5758bcff0eb16730b/src/chameleon/compiler.py#L224), which would be result in a huge ast tree description, that would be horrible to read.

Is that really what you want?

In how far would it be an advantage to my current solution in #247?

**Comment by malthe** [comment]
I don't think it would necessarily be very horrible. AST trees can be fairly compact.

In terms of advantage or not – I think code specified in a string is ... a little funky. But then again, all the emit functions are rather obscure.

**Comment by mrh1997** [comment]
testwise I created an AST from the python code. [The previous mention sample](https://github.com/mrh1997/chameleon/blob/da962ceb7b6a7d16660d0ba5758bcff0eb16730b/src/chameleon/compiler.py#L224) will resulte in hundrets of lines if unreadable and unmaintainable code.

i.E.
```
def func(target, quote, quote_entity, default, default_marker):
    if target is None:
        return
    if target is default_marker:
        return default
    __tt = type(target)
    ...
```

results in

```
Module(body=[
    FunctionDef(name='func', 
                args=arguments(args=[
                    Name(id='target', ctx=Param()), 
                    Name(id='quote', ctx=Param()), 
                    Name(id='quote_entity', ctx=Param()), 
                    Name(id='default', ctx=Param()), 
                    Name(id='default_marker', ctx=Param())], 
                    vararg=None, 
                    kwarg=None, 
                    defaults=[]), 
                body=[
                    If(test=Compare(left=Name(id='target', ctx=Load()), ops=[Is()], 
                                    comparators=[Name(id='None', ctx=Load())]), 
                       body=[Return(value=None)], orelse=[]), 
                    If(test=Compare(left=Name(id='target', ctx=Load()), 
                                    ops=[Is()], 
                                    comparators=[Name(id='default_marker', ctx=Load())]), 
                       body=[Return(value=Name(id='default', ctx=Load()))], 
                       orelse=[]), 
                    Assign(targets=[Name(id='__tt', ctx=Store())], 
                           value=Call(func=Name(id='type', ctx=Load()), 
                                      args=[Name(id='target', ctx=Load())], 
                                      keywords=[], starargs=None, kwargs=None)),
                   ...
```

Do you really persist on this kind of modification?

And: In how far is code in strings funky? You do it all over in your code. I.e. [here](https://github.com/mrh1997/chameleon/blob/da962ceb7b6a7d16660d0ba5758bcff0eb16730b/src/chameleon/compiler.py#L1056)

**Comment by malthe** [comment]
I guess you're right.

Thanks for making a clear case.

**Comment by mrh1997** [comment]
Do you need more input from me to merge #247 ?

**Comment by malthe** [comment]
Just needed to think it over. Thanks for reminding me!

**Comment by malthe** [comment]
This is now part of release 3.2.
