### ISSUE TITLE
Retrieving global variables from templates

### ISSUE THREAD

**Issue by tamarintech** [malthe/chameleon#248]
This is a special use-case, but I was hoping someone could point me in the right direction.

I have inherited some templates that start like this:
```
<defines tal:define="
global datepublished '2017-09-20';
global datecreated '2017-09-20';
global datemodified '2017-09-20';
```
Is there any way I can use the PageTemplateLoader class to inspect those templates and extract the globals out?

I have tried this:
```
from chameleon import PageTemplateLoader
loader =  PageTemplateLoader('templates')
template = loader['template1.pt']
```

But the defines don't show up in templates.builtins or similar after cooking/rendering.

**Comment by malthe** [comment]
You would have to render the templates to have a chance at seeing those
globals.

The econtext has a special reference I believe to globals defined using
“global”.

But in this case, Chameleon could be smart and see that the globals are
just constants. In reality, it just evaluates them at render-time.

**Comment by tamarintech** [comment]
Thanks for the answer. I sort of figured I was at a dead end, but it would have saved me some time on this project

Thanks! :)
