### ISSUE TITLE
Documentation: No support for repeat.item.first or repeat.item.last, remove that text?

### ISSUE THREAD

**Issue by jamadden** [malthe/chameleon#249]
The [docs claim](https://chameleon.readthedocs.io/en/latest/reference.html#repeat-variables) that a repeat item has a `first` and `last` attribute that's used for grouping. However, I don't find those attributes defined on the RepeatItem class, and trying to use them in a template results in either an AttributeError (in a Python expression) or a LocationError (in a path expression).

FWIW, I couldn't find where `first` and `last` were implemented for `zope.tales` and `zope.tal` despite the old [Zope2 reference](https://docs.zope.org/zope2/zope2book/AppendixC.html#repeat-variables) documenting those variables (and Zope2 itself uses zope.tal[es] these days), and the zope.pagetemplate implementation fails similarly.

It's not that I need them, it's just that they claimed that you could pass a grouping argument into `first` in a path expression:

> You can provide the path by passing it as a parameter, as in `python:repeat['item'].first(color)`
> or by appending it to the path from the repeat variable, as in `repeat/item/first/color`.

I was curious exactly how they were doing that because it seemed useful. I started out planning to try to implement those values for chameleon if I could find where they are implemented in zope, but since they don't seem to be implemented anywhere, I suspect this is just a case of the documentation being outdated and in need of update? If so I can submit a PR.

**Comment by malthe** [comment]
Those groups are just weird. I suggest we update the documentation with advice on how to use `itertools.groupby`.

**Comment by jamadden** [comment]
Ok. 

Am I correct that those groups aren’t actually even implemented (and should be removed from the docs)? Or is there some trick to using them that I’m missing? Saying “those groups are weird” is ambiguous to me 🙂

**Comment by malthe** [comment]
They're not implemented. I think because they don't have a reference implementation? I don't recall exactly.

**Comment by jamadden** [comment]
I found an implementation of them in [Zope2](https://github.com/zopefoundation/Zope/blob/2b88c016f12891f47ee8637caf965ef95c1cf6b7/src/Products/PageTemplates/Expressions.py#L327), where they are commented as "Zope 2 enhancements".
