### ISSUE TITLE
Latest documentation at chameleon.readthedocs.io is for version 2.10

### ISSUE THREAD

**Issue by jamadden** [malthe/chameleon#251]
http://chameleon.readthedocs.io/en/latest/ says it's for Chameleon 2.10. The [build status](http://readthedocs.org/projects/chameleon/builds/) says the latest branch was last build 1 year, 8 months ago. This is what you get if you simply go to http://chameleon.readthedocs.io/ , and it's explicitly linked to from https://pypi.python.org/pypi/Chameleon

There have been a lot of important changes to Chameleon and the documentation between now and then. One thing that immediately caught my eye was that the 2.10 ("latest") documentation says that `i18n:target` is ignored, while if you explicitly select the 3.1 documentation, it appears to be supported.

Maybe the RTD webhook is messed up? Can something be done to get the `/latest/` documentation to actually *be* the latest?

**Comment by malthe** [comment]
It's weird – I sometimes have to kick it explicitly.

**Comment by jamadden** [comment]
I've noticed that the latest docs are current again. Thank you.

Along these lines, `conf.py` has the version number hard-coded at 3.0. Many projects I've worked on (e.g, [zope.datetime]) use `pkg_resources` to avoid having to hard-code the version number:
```python
import os
import sys
import pkg_resources
sys.path.append(os.path.abspath('../src'))
rqmt = pkg_resources.require('zope.datetime')[0]
...
# The short X.Y version.
version = '%s.%s' % tuple(map(int, rqmt.version.split('.')[:2]))
# The full version, including alpha/beta/rc tags.
release = rqmt.version
```

This just requires that RTD's "install this project" or "install this requirement file" (with an appropriate requirements file) box is checked. If you'd like, I can submit a PR for this.

While checking this, I noticed that RTD is explicitly installing Chameleon=2.11 (from docs/requirements.txt) so it's likely that any autodoc-generated documentation is out of data; that could be changed in the same PR.

**Comment by malthe** [comment]
I think you're right that it does install `Chameleon==2.11`. I wonder what it uses it for though?

**Comment by jamadden** [comment]
I can't see any reason that it would do that. I mean, the project does need to be installed or at least on `sys.path` for autodoc (`..autoclass:`, etc) to work, and the docs do use that, but I don't know why it would have pinned a version like that.

Unless maybe there was a time when RTD didn't support the "install this project" setting, and *only* supported requirements files? But even then, the better option, IMO, is to point RTD to a `docs-requirements.txt` in the root directory that looks like:
```
.[docs]
```

That way you get the correct version (the checked-out version) and you DRY with regards to any additional deps you need for themes, sphinx extensions, etc.

PR #253 takes a crack at fixing this.

Sadly it looks like the 'latest' branch is still not auto-building. One thing I've sometimes found helpful is to go into the github settings and remove the integration with RTD, and then add it back.

**Comment by malthe** [comment]
I fixed the configuration and it now builds again.
