### ISSUE TITLE
UnboundLocalError: local variable '__condition' referenced before assignment

### ISSUE THREAD

**Issue by jinty** [malthe/chameleon#256]
I can't reproduce this, but posting here to see if it rings any bells for anyone.

Recently we had a load spike and a new server came up. Unfortunately, a template seems to have been mis-compiled resulting in the above error. We bring new servers up a lot and this is the only time it's failed, recompiling on the same server doesn't reproduce the error.

Specifically, the wrongly compiled code looks like:

```
              # <Value 'title' (7:25)> -> __condition
              __token = ('title', 7, 25, '.../content_expires_widget.pt', )
              __attr_value = getitem('title')                                                                                                         
              if __condition:
```

and the correctly compiled version is:

```
              # <Value 'title' (7:25)> -> __condition
              __token = ('title', 7, 25, '.../content_expires_widget.pt', )
              __condition = getitem('title')                                                                                                          
              if __condition:
```

The line of the template being compiled is:
```
                <legend tal:condition="title">${title}</legend>
```

To test if it's random, I'm re-compiling the template in a loop. I've done 3000 of those so far without reproducing.

**Comment by malthe** [comment]
Looks like a bug that might be triggered by garbage collection?

It is always possible that it's a memory error ... I wonder if compiling it a bazillion times with perhaps a dozen individual loaders would trigger the bug?

**Comment by jinty** [comment]
I'm not that familiar with the code so I can't imagine how garbage collection could affect this.

I tried a few thousand more times to reproduce it, no dice. Gonna mark it down to a cosmic ray, which is much cooler than a simple memory error ;)
