### ISSUE TITLE
Support HTML comments?

### ISSUE THREAD

**Issue by bratao** [malthe/chameleon#262]
Hello, 

I want to use chameleon in a HTML templates with browser conditionals like:

`<!--[if !mso]`

But chamaleon keep giving the error:
"The string '--' is not allowed in a comment."

Do chameleon supports HTML or just XML ?

**Comment by icemac** [comment]
I'm using HTML comments in Chameleon templates without problems.

Does your comment contain any additional `--` besides the ones in `<!--` and `-->`?
(See also http://www.htmlhelp.com/reference/wilbur/misc/comment.html which is implemented in Chameleon.)
