### ISSUE TITLE
Provide mechanism to log errors suppressed by on-error

### ISSUE THREAD

**Issue by rafaelbco** [malthe/chameleon#266]
I would like to be able to log errors suppressed by the `on-error` directive.

A non-intrusive way to achieve this would be to have a mechanism to register a callback (like an event handler) which would receive the error information. Then users of the template engine could log the errors any way they want.

Other nice thing that could be implemented is to re-raise errors that cannot be suppressed. For example, in applications running on top of ZODB it is not recommended to swallow `ConflictError` exceptions.

**Comment by malthe** [comment]
The code that compiles the `OnError` node looks like this:
```python
        body += [ast.TryExcept(
            body=self.visit(node.node),
            handlers=[ast.ExceptHandler(
                type=ast.Tuple(elts=[Builtin("Exception")], ctx=ast.Load()),
                name=store("__exc"),
                body=(error_assignment + \
                      template("del __stream[fallback:]", fallback=fallback) + \
                      fallback_body
                      ),
                )]
            )]
```
If you wanted a mechanism to observe and/or suppress this, then we could throw in an optional exception handler that takes the exception object as its only argument. It would then have the option itself of simply re-raising the exception such that `fallback_body` never runs and the whole thing catapults out of the block.

For logging purposes, perhaps some additional context would be good. There is of course the `econtext` dictionary. But perhaps that's too low level. It's sort of an implementation detail.

**Comment by rafaelbco** [comment]
Thank's a lot!
