### ISSUE TITLE
tal:repeat does not iterate through dictionary types using .items()

### ISSUE THREAD

**Issue by kveroneau** [malthe/chameleon#271]
In most template langauges you can iterate through a dictionary's key/value using something like this:

for key,value in my_dict.items()

This does not work in Chameleon, it raises a LanguageError: Invalid define syntax.

Should tal:repeat support this, or is it by design to not be supported?

**Comment by malthe** [comment]
![image](https://user-images.githubusercontent.com/26405/46901758-7ad74500-ceb9-11e8-866b-64015e15d430.png)

See https://chameleon.readthedocs.io/en/latest/reference.html.
