### ISSUE TITLE
How to define an i18n:name on an attribute?

### ISSUE THREAD

**Issue by gforcada** [malthe/chameleon#287]
Hi! Thanks for this wonderful template engine and all the cherries on top from plain ZPT!! :heart: 

I have the following template:

```
<a
    href="https://plone.org"
    tal:attributes="aria-label python:'Page ' + str(pagenumber)">
  ${pagenumber}
</a>
```

How can I add i18n support to the ``aria-label`` here? :thinking: I would need a ``i18n:name`` but that is on an attribute rather than on a tag :confused:

**Comment by malthe** [comment]
Use the `i18n:attributes` directive.

**Comment by gforcada** [comment]
That much I know, the problem is that the `aria-label` string has a variable on it.

**Comment by malthe** [comment]
I think what you need to do is to make the value used in `tal:attributes` by a `zope.i18n.Message` object which can then contain the variables necessary for the message.

You may or may not need to still "activate" translation via `i18n:attributes`.
