### ISSUE TITLE
Macro bodies echoed at definition time

### ISSUE THREAD

**Issue by DavidBarts** [malthe/chameleon#292]
Consider the following simple template:
```
<!DOCTYPE html>
<p metal:define-macro="test">
  This is a test macro.
</p>
<html>
  <head>
    <title>Macro Test</title>
  </head>
  <body>
    <h1>Macro Test</h1>
    <p metal:use-macro="macros['test']"></p>
  </body>
</html>
```

When rendered, it results in:
```
<!DOCTYPE html>
<p>
  This is a test macro.
</p>
<html>
  <head>
    <title>Macro Test</title>
  </head>
  <body>
    <h1>Macro Test</h1>
    <p>
  This is a test macro.
</p>
  </body>
</html>
```
If this is a bug, it needs to be fixed. If it is a feature, is there a way of disabling it? If it is a feature and there is no way of disabling it, there needs to be one! (And I'm willing to work on adding it.)

**Comment by malthe** [comment]
That’s a “feature”, carried over from Zope.

You can disable via an outer block that has tal:condition=“False”.

This works because macros are extracted out of context so to speak.

**Comment by DavidBarts** [comment]
Thanks! I thought it might be a feature. And thanks for the info on how to disable it.
