### ISSUE TITLE
Support for f-strings?

### ISSUE THREAD

**Issue by icemac** [malthe/chameleon#294]
When I try to use an f-string in a PageTemplate I get something like „Compilation failed
builtins.Exception: No handler for ``JoinedStr`“.

(I tried it in Zope 4 TTW so I did not get a traceback.)

Is this feature missing in Chameleon or does it "only" need to be fixed in the Zope integration layer?

**Comment by malthe** [comment]
Might be missing from Chameleon’s codegen tooling

**Comment by malthe** [comment]
Support added in 8e9fe9cb739d0acc13f717c51e1c9d5548d00b9d.

**Comment by icemac** [comment]
Cool, thank you!

**Comment by malthe** [comment]
If you can please check it out before I cut a release.
