### ISSUE TITLE
page templates vs. Chameleon

### ISSUE THREAD

**Issue by jugmac00** [malthe/chameleon#295]
One of the apps I maintain currently runs on Zope 2, but I am about upgrading it to Zope 4.

The app uses **page templates** and with Zope 4 **Chameleon** seems to be the new default.

I run into several problems - which I'd like to understand.

In the documentation you can read the following:

> If you’ve used page templates in a Zope environment previously, note that Chameleon uses Python as the default expression language (instead of path expressions).

Does this mean **path expressions** are no longer the default or **path expressions** will not work at all?

e.g. will this snippet work? `<b tal:content="here/className">className</b>`

Further I read ...

> The Zope reference engine defaults to a path expression type, which is closely tied to the Zope framework. This expression is not implemented in Chameleon (but it’s available in a Zope framework compatibility package, z3c.pt).

So, this really means all path expressions will fail?

Next bit of information in the documentation...

> The z3c.pt package works as a compatibility layer. The template classes in this package provide a implementation which is fully compatible with ZPT.

So, this means using z3c.pt path expressions should still work in a Zope 4 environment?

Unfortunately, I still see path related errors like the following...

```
2019-09-23 14:38:16,269 ERROR   [Zope.SiteErrorLog:251][waitress] 1569242296.270.682571782398 http://0.0.0.0:8084/bliss/data/Users/instances/jugmac00/preferences
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module Shared.DC.Scripts.Bindings, line 335, in __call__
  Module Shared.DC.Scripts.Bindings, line 372, in _bindAndExec
  Module Products.CMFCore.FSPageTemplate, line 249, in _exec
  Module Products.CMFCore.FSPageTemplate, line 190, in pt_render
  Module Products.PageTemplates.PageTemplate, line 85, in pt_render
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 88, in __call__
  Module z3c.pt.pagetemplate, line 173, in render
  Module chameleon.zpt.template, line 306, in render
  Module chameleon.template, line 209, in render
  Module chameleon.template, line 187, in render
  Module 6844a1a404e10f8444fbf373563a8fc3.py, line 523, in render
  Module Products.PageTemplates.expression, line 94, in __call__
  Module Products.PageTemplates.expression, line 65, in traverse
  Module zope.traversing.adapters, line 156, in traversePathElement
   - __traceback_info__: (None, 'msg')
  Module zope.traversing.adapters, line 61, in traverse
   - __traceback_info__: (None, 'msg', ())
LocationError: (None, 'msg')

 - Expression: "here/utils/msg"
 - Filename:   ... .git/src/Products/BlissEntities/www/User/preferences.xpt
 - Location:   (line 29: col 33)
 - Source:     ... n tal:replace="structure here/utils/msg">messageTable</span>
                                            ^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ImplicitAcquisitionWrapper preferences at 0x7f1c88cee550>
               modules: <_SecureModuleImporter - at 0x7f1ca23767d0>
               here: <ImplicitAcquisitionWrapper jugmac00 at 0x7f1c89f187d0>
               wrapped_repeat: {...} (1)
               user: <ImplicitAcquisitionWrapper jugmac00 at 0x7f1c88cee8c0>
               nothing: <NoneType - at 0x555f167f9560>
               container: <ImplicitAcquisitionWrapper jugmac00 at 0x7f1c89f187d0>
               default: <object - at 0x7f1caa603770>
               request: <WSGIRequest - at 0x7f1c8957a7d0>
               traverse_subpath: <list - at 0x7f1c89775560>
               loop: {...} (1)
               context: <ImplicitAcquisitionWrapper jugmac00 at 0x7f1c89f187d0>
               translate: <function translate at 0x7f1ca1f0d230>
               root: <ImplicitAcquisitionWrapper  at 0x7f1ca1f96820>
               options: {...} (1)
               target_language: <NoneType - at 0x555f167f9560>
```

Re-writing the expression to
`python: here.utils.msg()`
fixes the problem - but I'd like to understand why?

Almost all templates contain path expressions and still work (with z3c.pt), but only a handful fail... and I fail to understand why.

P.S.: I hope this is the correct repo - or should I file a ticket in https://github.com/zopefoundation/z3c.pt ?

**Comment by jugmac00** [comment]
**Update**
The above error only appears in the running instance, the testsuite passes. Which makes this even more mysterious to me.

**Comment by icemac** [comment]
Maybe this problem arises because of using `TrustedExecutables` (see preferences.xpt) which is not yet compatible with Chameleon.

**Comment by jugmac00** [comment]
@icemac Thank you. I am about wrapping up all the latest (massive) changes, and I'd like to close this issue until further notice (and until there was some more investigation in combination with TrustedExecutables).

What still puzzles me, is that the tests passes, but performing the same actions within the instance via browser GUI.. it works.
