### ISSUE TITLE
Parser/linter available?

### ISSUE THREAD

**Issue by jugmac00** [malthe/chameleon#300]
I am about migrating 500 page templates (Zope 2 syntax) to Chameleon.

Is there any linter/parser available which could check the syntax?

Or any other tip how to proceed? Unfortunately not all templates get covered by tests and not all are easily callable in the browser.

Thank you!

**Comment by malthe** [comment]
If you provide environment variable `CHAMELEON_EAGER=1` then file-based templates will be "cooked" (parsed and translated to Python byte-code) on initialization.

Alternatively, you can simply call `template.cook_check()` manually to the same effect.

**Comment by jugmac00** [comment]
Thank you very much!
