### ISSUE TITLE
"ExceptionFormatter"/"format_kwargs": provide customization for special application types

### ISSUE THREAD

**Issue by d-maurer** [malthe/chameleon#309]
As "https://github.com/zopefoundation/Zope/issues/837" describes, exception information is not optimal in a Zope context. This is because many objects are so called acquisition wrappers. `chameleon.utils.format_kwargs` does (understandably) not know this type and uses the uninformative representation via type name and address.

If `chameleon` would provide customization for `ExceptionFormatter` and/or `format_kwargs`, an integration could ensure proper representation for types with special importance, such as "acquisition wrapper"s for Zope.

**Comment by malthe** [comment]
@d-maurer can you take a look to see if this fits the bill?

I have simplified the code so the interface to implement is basically just `repr` or `pprint.pformat`. I believe earlier on, the code was using the latter but this tended to blow up in complexity for some values.

The value representation function today looks quite conservative, perhaps overly so.

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-5-27 00:02 -0700:
> ...
>I have simplified the code so the interface to implement is basically just `repr` or `pprint.pformat`. I believe earlier on, the code was using the latter but this tended to blow up in complexity for some values.

Would you mind to release a new version?

This would allow me to finalize
"https://github.com/zopefoundation/Zope/pull/839" (adding a test,
pinning the new `chameleon` version).

**Comment by malthe** [comment]
I have now released 3.7.2.

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-5-30 22:53 -0700:
>I have now released 3.7.2.

Thank you!
