### ISSUE TITLE
A definition for "attrs" is ignored

### ISSUE THREAD

**Issue by d-maurer** [malthe/chameleon#321]
The problem is demonstrated by the following transscript:
```
>>> t = PageTemplate("<div tal:define='attrs 1' tal:content='attrs' />")
>>> t()
'<div>{}</div>'
```
Expected output would by `<div>1</div>`.

I came to this analyzing "https://github.com/plone/Products.CMFPlone/issues/3135" - more precisely, why caused the switch from `chameleon.tales` to `zope.tales` in the `Zope` integration the loss of the `attrs` "variable" feature. Apparently, `chameleon` does not treat `attrs` as a (normal) variable (accessed via `econtext`) but handles it specially (I have not yet found out how precisely). The behavior above is a consequence of this special treatment - as is the loss of the `attrs` feature in the `Zope` integration.

**Comment by malthe** [comment]
I suppose what's also lost might be some performance?

Isn't the idea just to fall back to `zope.tales` for those providers which are not natively supported in [z3c.pt](https://pypi.org/project/z3c.pt/) - ?

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-7-2 03:08 -0700:
>I suppose what's also lost might be some performance?

Sure. But I doubt that the loss is significant.

A sigificant part of the TALES expressions in the Zope
world are "path" expressions (the default expression type).
For them, the evaluation is essentially delegated to a runtime
function -- in both cases.

The difference is most prominent for "python" expressions.
In this case, with `zope.tales` the expression is compiled
when the template is first used (in a process); the
result is likely comparable to the compilation result done
by `chameleon.tales`. There is a bit of overhead because
with `zope.tales` the expression is compiled into a function
(which must be called) while `chameleon.tales` generates inline
code (the call overhead is avoided). There are additional calls
necessary for the adaptation. Overall, we likely have a few
function calls as overhead.
Furthermore, `chameleon` typically uses a persistent compilation
cache. I.e. it can avoid the expression compilation per process run.


>Isn't the idea just to fall back to `zope.tales` for those providers which are not natively supported in [z3c.pt](https://pypi.org/project/z3c.pt/) - ?

Maybe, that would also have been an option.

But I found it very attractive to have a single TALES
implementation in the Zope world - and not one for
templates and another one for the CMF, `DCWorkflow`, some
portlets, ...

Having different TALES implementations comes with a risk.
For example, I have seen an error `you are not allowed to use "sorted"
in this context` with `zope.tales` which did not occur
with `chameleon.tales`. In the `Zope` world, `AccessControl`
decides what is allowed - and `AccessControl` does not allow `sorted`.
Thus, somewhere, `chameleon.tales` (more likely its integration)
does not honour the restrictions imposed by `AccessControl`.


For hours, I try to find out how (and where) `chameleon` distinguishes
between `attrs` and a "normal" variable.
In the final code, `attrs` is accessed via `LOAD_GLOBAL __attrs_<magic>`
while a normal variable is accessed via `LOAD_FAST econtext;
LOAD_CONST ...; SUBSCRIPT`. The expression itself does not
handle those cases differently -- in both cases, the
variable is represented by an `ast.Name`.
Apparently, the distinction is made later but where this happens
is hard to find.
Do you have a tip for me?

**Comment by malthe** [comment]
The access control restrictions most certainly _do apply_ to the `z3c.pt` integration. In Plone, Chameleon runs the exact same security rewriting that `zope.template` does.

If there's an issue there then it is a serious one which should be fixed.

In `z3c.pt` we try to be faithful to the existing providers but take a pragmatic approach as well, keeping the performance which made Chameleon attractive in the first place.

In Chameleon, `attrs` is defined as a built-in variable using:
```
nodes.Define(
    [nodes.Alias(["attrs"], STATIC_ATTRIBUTES or EMPTY_DICT)],
    inner,
)
```
It's defined as an alias to bind the value to a static dictionary appearing in the template source code.

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-7-2 15:09 +0000:
>The access control restrictions most certainly _do apply_ to the `z3c.pt` integration. In Plone, Chameleon runs the exact same security rewriting that `zope.template` does.

There is a test
(`Products.PageTemplates.tests.test_pagetemplate.TestPageTemplateFile.test_rr`)
which correctly fails after the switch to `zope.tales` (the test suite
currently skips it) and was formerly incorrectly successful.

I did not investigate and therefore do not know where the error
was introduced. It is possible that the error is neither
in `chameleon` nor in `z3c.pt` but in their integration into `Zope`.

>If there's an issue there then it is a serious one which should be fixed.
> ...


>In Chameleon, `attrs` is defined as a built-in variable using:
>```
>nodes.Define(
>    [nodes.Alias(["attrs"], STATIC_ATTRIBUTES or EMPTY_DICT)],
>    inner,
>)
>```
>It's defined as an alias to bind the value to a static dictionary appearing in the template source code.

Thank you for this tip!


"https://github.com/malthe/chameleon/issues/323"
seems to indicate that the `Define` above comes too late.
While it is early enough for the processing of `tal:content` (and
likely `tal:replace`) it seems too late for `tal:define`.

**Comment by dataflake** [comment]
Just wondering, is this discussion still pointing to an issue or has it become obsolete with all the changes in Chameleon 3.8.1?

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2020-7-12 01:45 -0700:
>Just wondering, is this discussion still pointing to an issue or has it become obsolete with all the changes in Chameleon 3.8.1?

I have added a note to the "Zope Book" (almost surely not yet published)
along the lines: "attrs" (and "default") is special; assignments have
undefined effects. Thus, as far as `Zope` is concerned, there is no
longer an issue.

**Comment by dataflake** [comment]
The documentation at zope.readthedocs.io, including the Zope Book, are tied to GitHub with a hook that rebuilds them on pushes, so your note showed up immediately.

**Comment by dataflake** [comment]
I'm closing this, Dieter updated the documentation on the Zope side.
