### ISSUE TITLE
"attrs" cannot be used as a predefined variable in "tal:define"

### ISSUE THREAD

**Issue by d-maurer** [malthe/chameleon#323]
The problem is demonstrated by the following transacript
```
>>> from chameleon.zpt.template import PageTemplate
>>> t_ok = PageTemplate("""<div attr="attr" tal:content="attrs['attr']"/>""")
>>> t_ok()
u'<div attr="attr">attr</div>'
>>> t_err = PageTemplate("""<div attr="attr" tal:define="x attrs['attr']" tal:content="x"/>""")
>>> t_err()
Traceback (most recent call last):
...
  File "/home/dieter/tmp/chameleon/src/chameleon/utils.py", line 437, in __getitem__
    raise NameError(key)
NameError: attrs

 - Expression: "attrs['attr']"
 - Filename:   <string>
 - Location:   (line 1: col 31)
 - Arguments:  repeat: <RepeatDict ('None',) at 0x7f53793bad50>
               target_language: <NoneType ('None',) at 0x5643135f2560>
```
While `attrs` works in `tal:content` (--> `t_ok`), it does not work in `tal:define` (--> `t_err`).

This means that `attrs` does not behave like a regular predefined variable according to "https://zope.readthedocs.io/en/latest/zopebook/AppendixC.html#built-in-names". It also makes it more difficult to fix "https://github.com/zopefoundation/Zope/issues/860".

**Comment by d-maurer** [comment]
Surprisingly, `attrs` can also not be used in `tal:replace` -- only in `tal:content`.

**Comment by malthe** [comment]
Can you give this a whirl?

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-7-3 00:52 -0700:
>Can you give this a whirl?

Even after several hours of debugging inside `chameleon`,
many things are still magical for me -- the intricate
interaction between "compiler", "macroprogram", "expression engine",
various "ast" level transformations, node annotations, local aliases,
...

For someone already familiar with the `chameleon` internals,
the necessary change may be easy: just ensure the "attrs" alias
definition becomes effective before the processing of `tal:define`
and `tal:replace` and not only before the processing of `tal:content`.
For me, many hours would be necessary to locate the places
to be changed. Thus, I am likely not the best person to do this.

**Comment by malthe** [comment]
@d-maurer sorry, I meant can you try out the patch that I submitted for this in #324.

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-7-3 01:43 -0700:
>@d-maurer sorry, I meant can you try out the patch that I submitted for this in #324.

A misunderstanding on my part: usually, I see only the email
notifications - and they do not tell me that there is a related PR/issue.
I will check your changes soon.

And a big compliment: you are really really fast in fixing problems!

**Comment by d-maurer** [comment]
Malthe Borch wrote at 2020-7-3 01:43 -0700:
>@d-maurer sorry, I meant can you try out the patch that I submitted for this in #324.

In my local environment, I switched to your branch
"patch/fix-static-attrs" and removed the workaround from
`Products.PageTemplates`.

Now the test
"Products.PageTemplates.tests.test_persistenttemplate.TestPersistent.test test_onerror_structure" is failing:
...
  File "/home/dieter/tmp/chameleon/src/chameleon/template.py", line 192, in render
    self._render(stream, econtext, rcontext)
  File "1e72a319e2c8db0fd7f96946cf29312c.py", line 140, in render
  File "/home/dieter/tmp/chameleon/src/chameleon/utils.py", line 437, in __getitem__
    raise NameError(key)
NameError: attrs

 - Expression: "python: '&lt;i&gt;error"
 - Filename:   foo
 - Location:   (line 1: col 35)
 - Arguments:  repeat: <Products.PageTemplates.engine.RepeatDictWrapper object at 0x7f7568988500>
               template: <ZopePageTemplate at /test_folder_1_/foo>
               modules: <Products.PageTemplates.ZRPythonExpr._SecureModuleImporter object at 0x7f756a4c1e10>
               here: <Folder at /test_folder_1_>
               user: <User 'test_user_1_'>
               nothing: None
               container: <Folder at /test_folder_1_>
               request: <HTTPRequest, URL=http://nohost>
               traverse_subpath: []
               default: <module 'chameleon.tales' from '/home/dieter/tmp/chameleon/src/chameleon/tales.py'>
               loop: {}
               context: <Folder at /test_folder_1_>
               error: <chameleon.tal.ErrorInfo object at 0x7f7568a31090>
               translate: <function translate at 0x7f756846eb50>
               root: <Application at >
               options: {'args': ()}
               target_language: None

Apparently, there are still expression evaluations outside
the validity of the "attrs" alias definition.
The test name suggests that this could apply to "tal:on-error".

Most "tal" commands (at least "define", "condition", "content",
"replace") are now within the scope of the "attrs" alias - and
make no longer a problem.

Note that `Products.PageTemplates` does not contain tests
for `tal:switch`. Recently, indications have been found
that the `default` handling change was not applied to `tal:switch`.
Maybe, this applies also to the `attrs` change.

**Comment by dataflake** [comment]
@d-maurer All the examples you provided now work with Chameleon 3.8.1, I believe this can be closed.
