### ISSUE TITLE
tal:content and tal:replace are sometimes treated as to be translated

### ISSUE THREAD

**Issue by viktordick** [malthe/chameleon#326]
We have seen some weird behavior when switching to Zope4 that seems to be related to the Chameleon cache.

We use a translation service that effectively delegates translation to a Python Script in the context of the page template in question. But for the sake of providing an MWE, I stripped it down to something that simply returns a fixed text whenever something is to be translated. You can find it at [https://github.com/perfact/Products.PerFactTranslationDomain/tree/dummy-translator.](url).

If using a page template like

    <p i18n:translate="">original text</p>

This correctly replaces the content of the `p` tag by `translated`.

However, sometimes it also replaces the content of

    <p tal:content="string:original text">something</p>

and the same with `tal:replace`. By trying to nail down the problem, I found that this happens if the Chameleon cache file for the given page template has been created by the currently running Zope instance. So if I create a new page template, the behavior can be observed. If I restart Zope, it is gone. If I stop Zope, clear the Chameleon cache and start it again, it can again be observed.

Trying to debug the issue, I found myself inside the Chameleon cache file in a code block like

        def __quote(target, quote, quote_entity, default, default_marker):
            __tt = type(target)
            if ((__tt is int) or (__tt is float) or (__tt is int)):
                target = str(target)
            else:
                if (__tt is bytes):
                    target = decode(target)
                else:
                    if (__tt is not str):
                        try:
                            target = target.__html__
                        except:
                            __converted = convert(target)
                            target = (str(target) if (target is __converted) else __converted)
                        else:
                            return target()
                if (target is not None):
                    ...

If we are in the restarted run (where `tal:replace` does not get translated), `target` is of type `str` (with content `original text`) and we land in the last branch of the evaluation, where the string is being escaped.

However, if the Chameleon cache was cleared before starting Zope, `target` is of type `<class 'chameleon.tokenize.Token'>`. Since such a `Token` does not have the `__html__` attribute, `convert(target)` is called, which somehow ends up calling the translation service.

There is one thing most probably broken here and one thing that I maybe simply am not using correctly: One is that the type of `target` changes depending on if there was already a Chameleon cache present when Zope was started, leading to different behaviors. The second is that the `econtext` given to the `render` function contains the fields

    {'__convert': functools.partial(<function PageTemplate.render.<locals>.translate at 0x7fb5b35e5af0>, target_language=None),
     '__decode': <function PageTemplate.render.<locals>.decode at 0x7fb5b35e5ca0>,
     '__on_error_handler': None,
     '__translate': <function PageTemplate.render.<locals>.translate at 0x7fb5b35e5af0>,
    ...

Not sure if `convert` should point to a `translate` function if there is a specific `__translate` field also which seems to be the correct one for calling tags with `i18n:translate`.

### Steps to reproduce

    python3 -m venv Zope4
    cd Zope4
    bin/pip install -r https://raw.githubusercontent.com/zopefoundation/Zope/4.5/requirements-full.txt
    bin/pip install https://github.com/perfact/Products.PerFactTranslationDomain@dummy-translator
    bin/mkwsgiinstance -d zope -u admin:admin
    bin/runwsgi zope/etc/zope.ini

Open a browser at `http://localhost:8080/manage_main` and provide the credentials `admin:admin`. Now add a page template `testpt` with the content

    <p tal:content="string:replaced text">original text</p>

and let it render (`http://localhost:8080/testpt`)

### Expected behavior

We should obtain a paragraph with the content `replaced text`.

### Actual behavior

On the first try, we obtain a paragraph with the content `translated`. If restarting Zope, we again obtain the expected behavior. If removing everything in `zope/var/cache/` and restarting Zope, we again obtain `translated`.

### Versions

As seen above, I took the newly released Zope 4.5 as starting point. It contains Chameleon 3.8.1

**Comment by malthe** [comment]
It seems like this has to do with the way TALES expressions are compiled and cached during the rendering of templates.

During Chameleon's parsing of the original template input, the TALES engine integrated in Products.PageTemplates is called with a `chameleon.tokenize.Token` as the expression string type and the result is cached for later use.

However, on a cold run, during the rendering of templates, the TALES engine is called again from inside the generated template code and this time there is no `chameleon.tokenize.Token` because there is no parsing happening at all.

To work around this issue, make sure `expression` is coerced to a string or unicode in `_compile_zt_expr`.

That said, the approach taken is quite different from how Chameleon was first imagined. The idea with expression compilers is that they generate code at compile time, not at render time (even if it is cached). I would imagine that quite a bit of performance is lost due to the extra function calls and scope changes.

**Comment by d-maurer** [comment]
> It seems like this has to do with the way TALES expressions are compiled and cached during the rendering of templates.
> 
> During Chameleon's parsing of the original template input, the TALES engine integrated in Products.PageTemplates is called with a `chameleon.tokenize.Token` as the expression string type and the result is cached for later use.

@malthe Following your explanation, I tried to reproduce the problem with a `Zope` template. But, so far, I failed. Apparently, the expression is not always a `Token` even for the initial compilation. Can you tell me how I can ensure that the expression is a `Token`?

My most elaborate reproduction trial is:
```
from Products.PageTemplates.PageTemplate import PageTemplate
from Products.PageTemplates.tests.util import useChameleonEngine
useChameleonEngine()
def translate(*args, **kw): return "translated"

from z3c.pt import pagetemplate; pagetemplate.fast_translate = translate

t = PageTemplate()
ts3 = """<p tal:replace="string:x">original text</p>"""
ts4 = """\
<p i18n:translate="">text</p>
""" + ts3
t.write(ts4)
t()
```
It correctly produces `<p>translated</p>\nx`, i.e. it translates where it should.

**Comment by d-maurer** [comment]
Up to now, I have tried to reproduce the problem with Python 2 - without success. Now I was successful with Python 3. Apparently, `chameleon` behaves differently in this regard for Python 2 and Python 3. In both cases, the *expression* is represented as a `Token` but for Python 3 this leads to a translation while for Python 2 this is not the case.

Small problem reproducing example for Python 3
```
from Products.PageTemplates.PageTemplate import PageTemplate
from Products.PageTemplates.tests.util import useChameleonEngine
useChameleonEngine()
def translate(*args, **kw): return "translated"

from z3c.pt import pagetemplate; pagetemplate.fast_translate = translate

t = PageTemplate()
ts5 = u"""<p tal:replace="string:x">original text</p>"""
t.write(ts5)
t()
```

I can work around this strange behavior in the `Zope/chameleon` integration. But, I consider it a bug in `chameleon`: the integration does nothing what cannot be done in a Python expression with stock `chameleon`; thus it should be possible to construct an example for stock `chameleon` which, too,  leads to wrong translations.
