### ISSUE TITLE
Provide wheels

### ISSUE THREAD

**Issue by jugmac00** [malthe/chameleon#330]
Hi,

currently `Chameleon` does not provide a wheel for PyPi, see https://pypi.org/project/Chameleon/#files

When I installed `Products.ZopeTree` today, I got the following warning:
```
...
Building wheels for collected packages: Chameleon
  WARNING: Building wheel for Chameleon failed: [Errno 13] Permission denied: '/home/jugmac00/.cache/pip/wheels/61/33'
Failed to build Chameleon
...
    Running setup.py install for Chameleon ... done
  DEPRECATION: Chameleon was installed using the legacy 'setup.py install' method, because a wheel could not be built for it. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
...
```

While this may be a problem in my local environment, maybe it is still a good idea to provide pre-packaged wheels?

**Comment by dataflake** [comment]
A first step is now done, in #334 I added a `setup.cfg` that specifies wheels as universal.  Just adding `bdist_wheel` when creating the release eggs and uploading them will do the right thing.

**Comment by icemac** [comment]
This ticket can be closed after a version > 3.8.1 is released containing #334.

**Comment by dataflake** [comment]
#334 is merged, but this is mostly a matter of the releasing person actually doing the additional `bdist_wheel` and uploading it. From the list of maintainers on PyPI I am guessing @malthe is the only person making releases now. @malthe would you consider adding me on PyPI (-> dataflake) as well?

**Comment by malthe** [comment]
I have added you as maintainer. Thanks! I'm just in Rust-world these days trying to become productive. The Python work I do is mostly data science-oriented.

**Comment by dataflake** [comment]
@malthe I don't mind taking over more responsibilities and making releases if that's fine with you. I'm not 100% up to speed on all the internals, but it's sufficient for maintenance and simple issues.

**Comment by dataflake** [comment]
I just released 3.9.0 as tarball and egg.

**Comment by jugmac00** [comment]
Thanks a lot!

**Comment by domdfcoding** [comment]
I can see the wheel for 3.9.0 but there are only sdists for the subsequent 3.9.1, 3.10.x, 4.0.0 and 4.0.1 releases.
