### ISSUE TITLE
use-macro and variables

### ISSUE THREAD

**Issue by goschtl** [malthe/chameleon#331]
Hi, 

i am pretty sure this should work. But it does not. Any ideas.

I call i macro here, and i try to access the variable k in the macro.
<div tal:define="k 'KLAS'"> <div metal:use-macro="view.template.macros['field-macro']"> </div> </div>

But it seems i can not get k. Any idea.
This is my macro:

<div metal:define-macro="field-macro" class="form-group">
  <span tal:content="k">
</div>

Thanks Christian

**Comment by icemac** [comment]
@goschtl Your bug report seems to be incomplete. The examples you are referring to are missing.

**Comment by goschtl** [comment]
@icemac you are right. i found the issue and forgot to close the ticket again. i will do it now
