### ISSUE TITLE
Q: how to make condition without the element itself?

### ISSUE THREAD

**Issue by bapcyk** [malthe/chameleon#359]
Hello, it's a question (not a bug).

I have an another template engine which support something like (XML):

```xml
%IF(IS_LINUX)%
<a ..../>
<b .../>
<c .../>
%ENDIF%
```

How can I do the same in Chameleon? As I understand something like:

```xml
<some tal:condition="IS_LINUX">
  <a ..../>
  <b .../>
  <c .../>
</some>
```

will be translated to XML:

```
<some>
  <a ..../>
  <b .../>
  <c .../>
</some>
```

when `IS_LINUX`, ie, `<some>` will be presented in the result? Right? Is it possible to have such a conditional block without to keep the element with `tal:condition` in the result?

**Comment by malthe** [comment]
Use `tal:omit-tag=""` or use `<tal:some condition="IS_LINUX" />`.
