### ISSUE TITLE
Wheel releases?

### ISSUE THREAD

**Issue by gforcada** [malthe/chameleon#365]
Would it be nice if new releases would not only keep the tar.gz releases but also have wheels available as well 😄

**Comment by icemac** [comment]
For the `zopefoundation` projects we use https://pypi.org/project/zest.releaser/ which makes the release process easier and automatically creates and uploads wheels.

**Comment by mauritsvanrees** [comment]
I see the `setup.cfg` has a `[bdist_wheel]` section, which is enough for `zest.releaser` to conclude that a wheel should be created and uploaded. Just run `fullrelease`.

**Comment by malthe** [comment]
34096ef58dba5ceb825d7428db7d96f4bb0c2a51 tried to shrink source distribution (excluding tests, etc.) but this doesn't seem to work. For the 4.0.0 release I have simply manually run:
```bash
$ rm -rf docs benchmark src/chameleon/tests
```
It would be nice to have a better process for this.

**Comment by icemac** [comment]
The tests should be part of the source distribution as upstream packaging for linux distributions like to run the tests for the sdist.

How much makes removing that three directories the sdist smaller?

**Comment by malthe** [comment]
108 vs 170 KB – not too much I guess.

**Comment by domdfcoding** [comment]
There was a wheel for 3.9.0 but then only sdists again for 3.9.1, 3.10.x, 4.0.0 and 4.0.1

**Comment by malthe** [comment]
There's now a wheel release for 4.1.0 – it does not contain tests.

**Comment by malthe** [comment]
Both the source and wheel distribution files are now generated as part of the main workflow action.

The next step is to automate the release workflow, see #399.
