### ISSUE TITLE
4.1.0 wheel doesn't work under Python 3.11

### ISSUE THREAD

**Issue by mcdonc** [malthe/chameleon#383]
I first noticed this when running ``pyramid_chameleon`` tests, but when you install Chameleon with a simple ``pip install chameleon`` under Python 3.11, the result can't be imported.  It can't be imported apparnetly because it uses the 3.10 wheel version from PyPI.  I think this is normal; newer Python versions can use wheels from older Python versions.  But for whatever reason, trying to import chameleon under Python 3.11 when it was installed using the 3.10 wheel produces the following error:

```
Python 3.11.0rc1 (main, Aug 12 2022, 10:02:14) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chameleon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: bad magic number in 'chameleon': b'o\r\r\n'
>>> 
```

When the package is installed under 3.11 using ```pip install https://files.pythonhosted.org/packages/a6/b3/a12f28e3a0ed85d2b953ab67dcba7983e6f6aed9c74f4faee2551c71dd20/Chameleon-4.1.0.tar.gz`` (bypassing the wheel), everything works.

Using the wheel under 3.10 works fine.

I think just removing the wheel from PyPI would resolve the issue; that said I don't really understand the issue, so this may recur.

https://github.com/malthe/chameleon/assets/125174/734a234a-a57c-449d-a23c-61026a585fc3

I'm attaching a movie which demonstrates the issue.

**Comment by mcdonc** [comment]
FWIW, you might take a look at https://github.com/Pylons/waitress/blob/main/tox.ini#L68 in order to build a wheel via ``tox -e build".  This seems to produce a proper wheel.

**Comment by malthe** [comment]
I have removed the wheel that included .pyc-files only – it was actually intentional but I had not considered the obvious downside, that those files are interpreter-specific.

And while the wheel had py310 in it, it would still get picked for Python 3.11.

**Comment by malthe** [comment]
I have uploaded a new wheel "Chameleon-4.1.0-py3-none-any.whl" – with .py-files instead – and tested it with Python 3.11.

It's a bit surprising to me that PyPi allows me to upload a new wheel after the initial release. I haven't thought very deep about it, but I would think that a 5-minute limit or so would be a wise policy.

**Comment by mcdonc** [comment]
Works now, thanks!
