### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [malthe/chameleon#384]
Is it possible next time on release new version make the github release to have entry on https://github.com/malthe/chameleon/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.
My automation process those notification trying make preliminary automated upgrade of building packages which allow save some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by malthe** [comment]
I have [manually added a release now](https://github.com/malthe/chameleon/releases/tag/4.1.0), but I will keep this issue open to automate using actions in the future.

**Comment by kloczek** [comment]
Thank you very much 👍 😄

**Comment by malthe** [comment]
Superceded by #399 which aims to automate the release workflow.
