### ISSUE TITLE
Tests are missing in 4.4.1 release

### ISSUE THREAD

**Issue by mgorny** [malthe/chameleon#398]
The 4.4.1 release is missing `src/chameleon/tests` subtree, effectively making it impossible to run tests. It also means that the wheels generated from sdist are different than ones generated from the git repository.

**Comment by malthe** [comment]
This was discussed also in #365 actually – the wheel releases don't have tests, but the source tarball does.

Ideally, the release process happens entirely on GitHub but I haven't had the time to sort that out yet.

**Comment by mgorny** [comment]
I don't understand this comment. `Chameleon-4.4.1.tar.gz` on PyPI doesn't include tests.

**Comment by malthe** [comment]
@mgorny it pains me to say this, but I had to publish a new 4.4.2 release which fixes this 4.4.1 release.

I believe both the tarball and wheel releases should now work as expected. I would love to automate this release workflow but just haven't found the time to do so yet. Thanks for your patience.

**Comment by mgorny** [comment]
Thank you!
