### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by Daverball** [malthe/chameleon#405]
Is there some interest to start using inline type annotations in Chameleon? While probably not that many people interact with the API of Chameleon and rather use it indirectly through an existing Framework, it would still be useful for the ones that do and it should also help with stability and improve the documentation for the public API.

Would you be open to accepting pull requests? If there's no interest I am happy to go with the third party stubs route, I've written and published stubs to typeshed for WebOb, WTForms, Fanstatic, greenlet, gevent, uWSGI and a few other smaller libraries. Chameleon would be next on my list of packages I'd like to have stubs for.

You could always go with separate stubs first and merge them in later, if you don't want to fully commit to inline stubs, but still would like to try it out. There is automated tooling support for it.

**Comment by malthe** [comment]
I'm happy to introduce type annotations, I think they're helpful.

But we'll need some tooling to support it, i.e. automated testing. Is [Mypy](https://mypy-lang.org/) the right tool here?

**Comment by Daverball** [comment]
Yes, mypy is the de facto reference implementation of a Python type checker. Although if you want to support VSCode users, then supporting pyright in addition to mypy can be a good idea, since pyright is used by pylance. Although generally pyright tends to be a superset of mypy when it comes to feature completeness, rather than a subset and most the differences beyond that are negligible for end users.

typeshed (which hosts stubs for the standard library and some third party libraries) officially supports mypy, pyright and pytype.

Are you open to pull requests or would you prefer to do it yourself so you can learn as you go? You could also use something like https://github.com/JelleZijlstra/autotyping to get you started with minimal inline stubs.

Note that you will need to include a `py.typed` marker in your distribution so type checkers pick up the stubs, before that they will be treated as internal stubs.

**Comment by malthe** [comment]
No please, pull requests very welcome. I think the emphasis should be on supporting the public interface, but it might be useful to extend to some of the inner workings as well.

**Comment by Daverball** [comment]
One potential point of contention is the use of `zope.interface`, since it requires a mypy plugin in order to work correctly. It looks like `zope.inteface` is an optional dependency though, what are you using it for, testing?

This could be replaced by a `Protocol` or `ABC`, if you are open to getting rid of `zope.interface`. Unless third party libraries rely on those interfaces somehow, but I couldn't really find any references to the interfaces outside of the two classes that implement them.

**Comment by malthe** [comment]
We can lose the `chameleon.interfaces` module.

The one consumer that I know of [can be adapted](https://github.com/zopefoundation/z3c.pt/pull/25) to provide its own interface declaration.
