### ISSUE TITLE
PageTemplateLoader constructor no longer accepts default_extension as a positional argument in v4.5.0

### ISSUE THREAD

**Issue by rtasarz** [malthe/chameleon#411]
As in the title, it looks like adding type annotations messed it up. In version 4.2.0, it worked fine. Providing it as a keyword silences an exception, but I'm not sure if it works as intended then as my code currently uses full file names (so I'm dropping this argument from my invocations anyway).

**Comment by malthe** [comment]
See https://github.com/malthe/chameleon/releases/tag/4.5.1.
