### ISSUE TITLE
How to Have a placeholder preceded immediatly by a $

### ISSUE THREAD

**Issue by brianread108** [malthe/chameleon#422]
I am looking to expand $$${place} to $fred where place='fred'

but am finding that the renderer does not expand the ${place} at all in these circumstances and I get '${place}'. 

I am not sure if this is a bug or whether I have got it wrong.

**Comment by malthe** [comment]
Looks like a bug – The first two $-symbols should probably render as "$", and then `${place}` should render as usual.

**Comment by brianread108** [comment]
I'm post-processing the string currently .replace('$ ', '$') - Horrible!

**Comment by brianread108** [comment]
Fixed - many thanks
