### ISSUE TITLE
Can you put a placeholder inside a placeholder?

### ISSUE THREAD

**Issue by brianread108** [malthe/chameleon#424]
I'm looking for this to work : ${placeholder | ${Name}}

I get a syntax error.  Is there a format that will do it?

**Comment by brianread108** [comment]
aha - "${placeholder | '${Name}'}" does allow me through.

**Comment by brianread108** [comment]
But I get expanded to "${Name}" in the default. Not what I wanted.

Perhaps a second run through Chameleon would then expand it?

**Comment by malthe** [comment]
The term `placeholder` makes me confused here. The pipe operator is a fallback that catches `NameError`, but also other exceptions such as `KeyError`.

You could say `${does_not_exist | name}` – not sure what your `placeholder` is supposed to mean exactly.

**Comment by brianread108** [comment]
Yes, sorry I understand your confusion.  I am generating Mojolicious template entries, and "placeholder" is the HTML attribute of an INPUT tag. 

However you have given me the answer! Thanks - it works!
