### ISSUE TITLE
I need help with extracting data table from a defaultdict(int) 

### ISSUE THREAD

**Issue by brianread108** [malthe/chameleon#426]
Here is my template code:
```html
<table border="1">
  <thead>
    <tr>
      <th>Item</th>
      <th>Count</th>
    </tr>
  </thead>
  <tbody>
    <tr tal:repeat="item data.items()" tal:define="key item[0]; value item[1]">
      <td>${key}</td>
      <td>${value}</td>
    </tr>
  </tbody>
</table>
```
and I get this:
```
Error during rendering: item
 - Expression: "item.key()"
 - Filename:   <string>
 - Location:   (line 18: col 63)
 - Arguments:  data: {...} (3)
               target_language: <NoneType ('None',) at 0x58438d4803e0>
               repeat: <RepeatDict ('None',) at 0x7dd8cb16ed10>
```
I'm trying to show the key in the first column and the corresponding entries in the list in the following columns.

**Comment by malthe** [comment]
Unfortunately, `tal:define` is evaluated before `tal:repeat` – but you can use tuple-unpacking instead:

    tal:repeat="(key, value) data.items()"

See https://github.com/malthe/chameleon/blob/master/src/chameleon/tests/inputs/030-repeat-tuples.pt for a test case that demonstrates this.
