### ISSUE TITLE
zope.traversing.interfaces.ITraversable violation

### ISSUE THREAD

**Issue by dokai** [malthe/chameleon#59]
The `ITraversable` interface defines the the `traverse` method's `furtherPath` parameter as "a list of names still to be traversed. This method is allowed to change the contents of furtherPath."

However, when used in Plone 4.1 the `furtherPath` parameter is a tuple instead of a list which makes it impossible for the ITraversable implementation to modify it.

I noticed this when writing a view template for a Dexterity type that uses path traversal to render an image tag by traversing to  a plone.namedfile image (e.g. @@images/image/thumb). The  `ITraversable` implementation in `plone.namedfile.scaling.ImageScaling` attempts to .pop() the furtherPath which fails because it is a tuple.

Components used: Chameleon 2.4.4, z3c.pt 2.1.4, five.pt 2.1.5, Plone 4.1, plone.namedfile 1.0.4

**Comment by malthe** [comment]
This is a bug in `plone.app.imaging` and a fix has been released.
