### ISSUE TITLE
TAL incompatible repeat options

### ISSUE THREAD

**Issue by projekt01** [malthe/chameleon#70]
z3c.pt and chameleon are not fully compatible right now ith TAL. Traversing the repeat wrapper is not done the same way. ZPT uses the following pattern:

```
<tal:block condition="not:repeat/value/end">, </tal:block>

Chameleon only supports python style traversing at the moment:
<tal:block condition="not:python:repeat['value'].end">, </tal:block>
```

This is a problem in z3c.form select display widget template,
z3c/form/browser/select_diplay.pt

Versions:
Chameleon 2.0 and up, related z3c.pt versions

**Comment by malthe** [comment]
Closing the issue.
