### ISSUE TITLE
python 3 (pyramid 1.3 default) installation 

### ISSUE THREAD

**Issue by adroullier** [malthe/chameleon#78]
The installation shows a few python 3 SyntaxErrors. Though, installation works and everything seems to be ok:

Searching for Chameleon>=1.2.3
Reading http://pypi.python.org/simple/Chameleon/
Reading http://www.pagetemplates.org/
Reading http://chameleon.repoze.org
Best match: Chameleon 2.7.0
Downloading http://pypi.python.org/packages/source/C/Chameleon/Chameleon-2.7.0.tar.gz#md5=17dbb6b260d4c0c11848379cd3c33817
Processing Chameleon-2.7.0.tar.gz
Running Chameleon-2.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-iq32v5/Chameleon-2.7.0/egg-dist-tmp-2qj572
  File "build/bdist.linux-i686/egg/chameleon/benchmark.py", line 370
    @benchmark(u"BIGTABLE [python]")
                                  ^
SyntaxError: invalid syntax

  File "build/bdist.linux-i686/egg/chameleon/py25.py", line 4
    except AttributeError, exc:
                         ^
SyntaxError: invalid syntax

  File "/home/ad/data/work/dev/pyramid313/lib/python3.2/site-packages/Chameleon-2.7.0-py3.2.egg/chameleon/benchmark.py", line 370
    @benchmark(u"BIGTABLE [python]")
                                  ^
SyntaxError: invalid syntax

  File "/home/ad/data/work/dev/pyramid313/lib/python3.2/site-packages/Chameleon-2.7.0-py3.2.egg/chameleon/py25.py", line 4
    except AttributeError, exc:
                         ^
SyntaxError: invalid syntax

Adding Chameleon 2.7.0 to easy-install.pth file

**Comment by malthe** [comment]
This should no longer be an issue.
