### ISSUE TITLE
Errors do not indicate position in macro-templates

### ISSUE THREAD

**Issue by wichert** [malthe/chameleon#87]
I have a template which uses another template which defines a bunch of METAL macros. When there is an error in one of those macros Chameleon raises an exception which provides the position of the calling template, but does not indicate on what position in the macro-template the error occurs.

```
ExpressionError: unexpected EOF while parsing

 - String:   "'checked' if option[2] None"
 - Filename: templates/snippets.pt

 - Expression: "snippets['text']"
 - Filename:  templates/settings.pt
 - Location:   (12:62)

 - Source:     ... 'firstname'" use-macro="snippets['text']"/>
```

It would be helpful if there was Location-data for the snippets.pt error.

**Comment by malthe** [comment]
Please re-open with a minimal example.
